extends Node
## AudioDirector autoload — central owner of BGM / Ambient music transitions.
##
## **What this autoload does** (M2 W3 T9 — ClickUp `86c9uf6hh`):
##   1. Owns three `AudioStreamPlayer` nodes for global non-positional cues:
##        - `_bgm_player` → BGM bus (stratum BGM, boss music)
##        - `_ambient_player` → Ambient bus (room ambient bed)
##        - `_bgm_crossfade_player` → BGM bus, used for boss-room crossfades
##          (the outgoing track fades on `_bgm_player`, the incoming track
##          fades in on this player, then they swap roles).
##   2. Exposes high-level intent methods that other systems call by name:
##        - `play_stratum2_bgm(fade_in_ms)` — S1→S2 transition BGM
##        - `play_stratum2_ambient(fade_in_ms)` — S1→S2 transition Ambient
##        - `crossfade_to_boss_stratum2(fade_ms)` — boss-room music swap
##        - `stop_all_music(fade_out_ms)` — global stop (death, descend)
##   3. Lazy-loads `AudioStreamOggVorbis` resources on first use so a cold
##      boot doesn't pay the decode cost up front.
##
## **Why an autoload (not a Main.gd member):** every stratum-transition,
## boss-room load, and player-death event needs to reach the audio plumbing
## from a distinct call site. Routing them all through `Main.gd` would
## couple the audio to the M1 play-loop scene (which is itself getting
## torn down + rebuilt on respawn). An autoload survives scene-tree swaps
## and is reachable as `AudioDirector.play_stratum2_bgm()` from any node.
##
## **HTML5 audio-playback gate** (`team/uma-ux/audio-direction.md` and
## PR #210's deferred-to-Devon note): browsers gate `AudioContext` activation
## behind a user-gesture (a click, keypress, or touch). Until the player
## interacts with the page, ALL audio is silently silenced — `play()` succeeds
## from the engine's perspective but no sound emits. Embergrave currently
## boots straight into Stratum1Room01 (no menu / no title screen), so the
## first audio cue MUST fire AFTER the player has pressed at least one key.
## This is OK in practice because the S2 BGM / Ambient fires from the descend
## screen's "Return to Stratum 1" button — which IS a user gesture — and
## subsequent cues inherit the unlocked AudioContext. The first-cue-before-
## gesture path (if any future cue fires from `_ready`) needs an explicit
## `AudioContext.resume()` hook; intentionally not added now.
##
## **Test surface** (paired tests):
##   - `tests/test_audio_bus_layout.gd` — bus existence + dB values
##   - `tests/integration/test_s2_audio_triggers.gd` — S2 entry cues fire on
##     the right buses with the right streams
##
## **Decision honored:** Uma's UNIQUE (not cross-stratum-reuse) boss-music
## decision is preserved here — `crossfade_to_boss_stratum2()` loads
## `mus-boss-stratum2.ogg`, NOT `mus-boss-stratum1.ogg`. See
## `team/DECISIONS.md` 2026-05-15 entry.

# ---- Constants --------------------------------------------------------

const BUS_BGM: StringName = &"BGM"
const BUS_AMBIENT: StringName = &"Ambient"
const BUS_SFX: StringName = &"SFX"
const BUS_UI: StringName = &"UI"

## Cue resource paths. Match the filenames Uma shipped in PR #210.
const STREAM_PATH_S2_BGM: String = "res://audio/music/stratum2/mus-stratum2-bgm.ogg"
const STREAM_PATH_S2_BOSS: String = "res://audio/music/stratum2/mus-boss-stratum2.ogg"
const STREAM_PATH_S2_AMBIENT: String = "res://audio/ambient/stratum2/amb-stratum2-room.ogg"

## M3W-7 — SFX cue id → resource path map. Cue ids are stable StringName
## constants; consumers (Player, Grunt, Charger, Shooter, Stratum1Boss) call
## `AudioDirector.play_sfx(SFX_*)` so a rename of the underlying file (e.g.
## M4 promotion from algorithmic placeholder to freesound asset) is a
## single-line map edit — no consumer-side touchpoint.
##
## All cues route to the SFX bus (-6 dB per `audio-direction.md §3`).
## Placeholder synthesis disclosure: every SFX cue below is an algorithmic
## placeholder generated by `audio/_src/composer/compose_sfx_m3w7.py` per the
## established Uma S2-placeholder pattern (audio-direction.md §6). M4 promotes
## these to freesound + hand-Foley sourced finals.
const SFX_PLAYER_ATTACK_LIGHT: StringName = &"sfx-player-attack-light"
const SFX_PLAYER_ATTACK_HEAVY: StringName = &"sfx-player-attack-heavy"
const SFX_PLAYER_HIT: StringName = &"sfx-player-hit"
const SFX_PLAYER_DODGE: StringName = &"sfx-player-dodge"
const SFX_MOB_HIT: StringName = &"sfx-mob-hit"
const SFX_MOB_DIE: StringName = &"sfx-mob-die"
const SFX_BOSS_DIE: StringName = &"sfx-boss-die"
const SFX_ATTACK_TELEGRAPH: StringName = &"sfx-attack-telegraph"
const SFX_ATTACK_IMPACT: StringName = &"sfx-attack-impact"

const SFX_PATHS: Dictionary = {
	SFX_PLAYER_ATTACK_LIGHT: "res://audio/sfx/player/sfx-player-attack-light.ogg",
	SFX_PLAYER_ATTACK_HEAVY: "res://audio/sfx/player/sfx-player-attack-heavy.ogg",
	SFX_PLAYER_HIT: "res://audio/sfx/player/sfx-player-hit.ogg",
	SFX_PLAYER_DODGE: "res://audio/sfx/player/sfx-player-dodge.ogg",
	SFX_MOB_HIT: "res://audio/sfx/mobs/sfx-mob-hit.ogg",
	SFX_MOB_DIE: "res://audio/sfx/mobs/sfx-mob-die.ogg",
	SFX_BOSS_DIE: "res://audio/sfx/mobs/sfx-boss-die.ogg",
	SFX_ATTACK_TELEGRAPH: "res://audio/sfx/mobs/sfx-attack-telegraph.ogg",
	SFX_ATTACK_IMPACT: "res://audio/sfx/mobs/sfx-attack-impact.ogg",
}

## SFX pool size. Each pool entry is one `AudioStreamPlayer` on the SFX bus;
## a request rotates through the pool so a rapid second cue (e.g. mob-hit
## fires while a previous mob-hit is mid-decay) doesn't truncate the first.
## 8 entries handles every M3W-7 burst case observed in soak: 3-mob room
## with concurrent hit + die + telegraph + impact overlap stays inside the
## ring. If a future M4+ cue surface adds higher concurrency, bump this.
const SFX_POOL_SIZE: int = 8

## Default fade durations per `audio-direction.md §3 ducking rule 4`.
const DEFAULT_FADE_IN_MS: int = 600
const DEFAULT_FADE_OUT_MS: int = 600
const DEFAULT_CROSSFADE_MS: int = 600

## Silence floor (dB) for fade-out. -80 dB is effectively inaudible; we never
## tween to -INF because Tween cannot interpolate to it.
const SILENCE_DB: float = -80.0

## Bus volume at full-target — the bus's own offset (BGM = -12 dB etc.) is
## applied on top of this, so we keep player nodes at 0 dB at peak.
const FULL_DB: float = 0.0

# ---- Runtime ----------------------------------------------------------

var _bgm_player: AudioStreamPlayer = null
var _bgm_crossfade_player: AudioStreamPlayer = null
var _ambient_player: AudioStreamPlayer = null

# Active fade tweens — kept so a new transition can kill the in-flight tween
# without orphan-tween leakage.
var _bgm_fade_tween: Tween = null
var _bgm_crossfade_tween: Tween = null
var _ambient_fade_tween: Tween = null

# Cached streams. Loaded once on first use; the stream object is shared
# between cues since `AudioStreamPlayer` doesn't mutate it.
var _stream_s2_bgm: AudioStream = null
var _stream_s2_boss: AudioStream = null
var _stream_s2_ambient: AudioStream = null

# M3W-7 SFX pool — N AudioStreamPlayers rotating round-robin so concurrent
# cues don't truncate each other. Per-cue streams are cached in `_sfx_streams`
# keyed by cue id; the first `play_sfx(id)` call pays the `.ogg` decode cost,
# subsequent calls reuse.
var _sfx_pool: Array[AudioStreamPlayer] = []
var _sfx_pool_index: int = 0
var _sfx_streams: Dictionary = {}  # StringName cue_id → AudioStream

# Stable trace flag so we don't spam DevTools on every play() call when
# there's no actual surface change — set once per logical transition.
var _last_bgm_path: String = ""
var _last_ambient_path: String = ""

# Last SFX cue id played — test surface for paired-assert and harness-trace
# scoping. StringName ("") sentinel means no SFX played yet this lifetime.
var _last_sfx_id: StringName = &""


func _ready() -> void:
	_build_players()
	_build_sfx_pool()
	# Boot trace — proves the autoload registered + the bus indices resolved.
	# Same pattern as DebugFlags.gd's _ready trace.
	print("[AudioDirector] ready — bgm_bus=%d ambient_bus=%d sfx_bus=%d ui_bus=%d sfx_pool=%d" % [
		AudioServer.get_bus_index(BUS_BGM),
		AudioServer.get_bus_index(BUS_AMBIENT),
		AudioServer.get_bus_index(BUS_SFX),
		AudioServer.get_bus_index(BUS_UI),
		_sfx_pool.size(),
	])


# ---- Public API ------------------------------------------------------

## Start S2 BGM with a fade-in on the BGM bus. Idempotent: if S2 BGM is
## already the active stream, this is a no-op.
func play_stratum2_bgm(fade_in_ms: int = DEFAULT_FADE_IN_MS) -> void:
	if _last_bgm_path == STREAM_PATH_S2_BGM and _bgm_player != null and _bgm_player.playing:
		return
	var stream: AudioStream = _get_stream_s2_bgm()
	if stream == null:
		return
	_play_with_fade_in(_bgm_player, stream, fade_in_ms)
	_last_bgm_path = STREAM_PATH_S2_BGM
	_combat_trace("AudioDirector.play_stratum2_bgm",
		"stream=%s fade_in_ms=%d" % [STREAM_PATH_S2_BGM, fade_in_ms])


## Start S2 Ambient with a fade-in on the Ambient bus. Idempotent.
func play_stratum2_ambient(fade_in_ms: int = DEFAULT_FADE_IN_MS) -> void:
	if _last_ambient_path == STREAM_PATH_S2_AMBIENT and _ambient_player != null and _ambient_player.playing:
		return
	var stream: AudioStream = _get_stream_s2_ambient()
	if stream == null:
		return
	_play_with_fade_in_ambient(_ambient_player, stream, fade_in_ms)
	_last_ambient_path = STREAM_PATH_S2_AMBIENT
	_combat_trace("AudioDirector.play_stratum2_ambient",
		"stream=%s fade_in_ms=%d" % [STREAM_PATH_S2_AMBIENT, fade_in_ms])


## Convenience: fire the full S1→S2 transition (BGM + Ambient) in one call.
## This is the canonical Main.gd / DescendScreen entry-point.
func play_stratum2_entry() -> void:
	play_stratum2_bgm()
	play_stratum2_ambient()


## Crossfade BGM from whatever's currently playing to `mus-boss-stratum2`
## over `fade_ms`. The outgoing player fades to silence, the incoming
## (crossfade) player fades up — at the end they swap roles so future calls
## continue to operate on `_bgm_player`.
##
## Honors Uma's UNIQUE boss-music decision (`team/DECISIONS.md` 2026-05-15) —
## this targets `mus-boss-stratum2.ogg`, not the S1 boss music.
func crossfade_to_boss_stratum2(fade_ms: int = DEFAULT_CROSSFADE_MS) -> void:
	if _last_bgm_path == STREAM_PATH_S2_BOSS and _bgm_player != null and _bgm_player.playing:
		return
	var stream: AudioStream = _get_stream_s2_boss()
	if stream == null:
		return
	_crossfade_bgm(stream, fade_ms)
	_last_bgm_path = STREAM_PATH_S2_BOSS
	_combat_trace("AudioDirector.crossfade_to_boss_stratum2",
		"stream=%s fade_ms=%d" % [STREAM_PATH_S2_BOSS, fade_ms])


## M3W-7 — fire a one-shot SFX cue by id. Routes to the SFX bus via a
## round-robin pool so concurrent cues don't truncate each other.
##
## **Idempotence: NONE intentionally.** Combat cues are fire-and-forget —
## the caller (a signal handler on `damaged`, `mob_died`, `attack_spawned`,
## etc.) wants every emission audible. The dedupe burden is on the signal
## producer (e.g. `_is_dead` early-return on the second hit so `damaged`
## fires once per logical hit). The BGM/Ambient idempotence path here is
## fundamentally different — those track sustained state, not one-shot
## events.
##
## **HTML5 audio-playback gate** (per `audio-architecture.md`): combat
## input is itself a user gesture, so SFX cues fired from combat-signal
## handlers unlock the AudioContext on first emission. Cues fired before
## any user input (e.g. mob `_ready` autoplay) would be silenced by the
## browser. No M3W-7 cue site is in that path — all cues route from
## gameplay signals (`attack_spawned`, `mob_died`, etc.) that necessarily
## come after the player has pressed at least one key.
##
## **Cue id unknown:** safe no-op + `[combat-trace]` line so a typo or
## stale rename surfaces in soak traces rather than crashing.
func play_sfx(cue_id: StringName) -> void:
	if not SFX_PATHS.has(cue_id):
		_combat_trace("AudioDirector.play_sfx",
			"UNKNOWN cue_id=%s — check SFX_PATHS map" % cue_id)
		return
	var stream: AudioStream = _get_sfx_stream(cue_id)
	if stream == null:
		return
	var player: AudioStreamPlayer = _next_sfx_player()
	if player == null:
		return
	player.stream = stream
	player.play()
	_last_sfx_id = cue_id
	_combat_trace("AudioDirector.play_sfx",
		"cue_id=%s pool_index=%d" % [cue_id, _sfx_pool_index])


## Stop ALL global music + ambient with a fade-out. Used by player-death
## (Beat A: BGM hard-mutes) and any future "leave to title" path.
func stop_all_music(fade_out_ms: int = DEFAULT_FADE_OUT_MS) -> void:
	if _bgm_player != null and _bgm_player.playing:
		_fade_out_and_stop(_bgm_player, fade_out_ms)
	if _bgm_crossfade_player != null and _bgm_crossfade_player.playing:
		_fade_out_and_stop(_bgm_crossfade_player, fade_out_ms)
	if _ambient_player != null and _ambient_player.playing:
		_fade_out_and_stop(_ambient_player, fade_out_ms)
	_last_bgm_path = ""
	_last_ambient_path = ""


# ---- Test surface ----------------------------------------------------

## Returns the BGM AudioStreamPlayer. Used by paired tests to assert which
## stream is playing on which bus without find_child traversal.
func get_bgm_player() -> AudioStreamPlayer:
	return _bgm_player


## Returns the Ambient AudioStreamPlayer.
func get_ambient_player() -> AudioStreamPlayer:
	return _ambient_player


## Returns the BGM crossfade companion player.
func get_bgm_crossfade_player() -> AudioStreamPlayer:
	return _bgm_crossfade_player


## Returns the resource path of the last BGM stream we kicked off. Empty
## string before the first call. Useful for the integration test's "did
## the S2 trigger actually fire?" assertion.
func get_last_bgm_path() -> String:
	return _last_bgm_path


func get_last_ambient_path() -> String:
	return _last_ambient_path


## M3W-7 test surface — returns the cue id of the last SFX played, or &""
## if no SFX has played yet. Tests assert on this to confirm the signal
## handler actually called play_sfx with the right id.
func get_last_sfx_id() -> StringName:
	return _last_sfx_id


## M3W-7 test surface — returns the SFX pool size so paired tests don't
## need to know the const. (Bumping SFX_POOL_SIZE shouldn't break tests.)
func get_sfx_pool_size() -> int:
	return _sfx_pool.size()


## M3W-7 test surface — returns the round-robin player at `index` for
## paired tests that want to assert which player kicked the cue.
func get_sfx_pool_player(index: int) -> AudioStreamPlayer:
	if index < 0 or index >= _sfx_pool.size():
		return null
	return _sfx_pool[index]


## M3W-7 — test-only reset between paired tests. The round-robin index
## persists across calls; tests that need a known starting position call
## this in before_each.
func reset_sfx_pool_index_for_test() -> void:
	_sfx_pool_index = 0
	_last_sfx_id = &""


## Test-only: deterministically tear down the fade tweens + snap each player
## to its target state. Lets tests assert end-state without wall-clock waits.
##
## Crucial subtlety: `Tween.kill()` does NOT fire the tween's `finished`
## signal. The crossfade's role-swap is wired to `finished` (so the canonical
## `_bgm_player` reference points at the new track after the fade). If a
## test kills the crossfade tween without manually triggering the swap, the
## role-swap never happens and the test asserts a stale state. We solve that
## by snapping volumes first, then manually invoking the finalize callback
## if a crossfade tween was in flight — same end-state as letting the tween
## complete naturally, but deterministic for headless tests.
func complete_pending_fades_for_test() -> void:
	var had_crossfade_in_flight: bool = (
		_bgm_crossfade_tween != null and _bgm_crossfade_tween.is_valid()
	)
	if _bgm_fade_tween != null and _bgm_fade_tween.is_valid():
		_bgm_fade_tween.kill()
	if _bgm_crossfade_tween != null and _bgm_crossfade_tween.is_valid():
		_bgm_crossfade_tween.kill()
	if _ambient_fade_tween != null and _ambient_fade_tween.is_valid():
		_ambient_fade_tween.kill()
	# Snap volumes to the target before swap so the finalize observes the
	# expected end-state.
	if _bgm_player != null and _bgm_player.playing:
		_bgm_player.volume_db = FULL_DB
	if _ambient_player != null and _ambient_player.playing:
		_ambient_player.volume_db = FULL_DB
	if had_crossfade_in_flight and _bgm_crossfade_player != null \
			and _bgm_crossfade_player.playing:
		_bgm_crossfade_player.volume_db = FULL_DB
		_finalize_crossfade()


# ---- Internal --------------------------------------------------------

func _build_players() -> void:
	_bgm_player = AudioStreamPlayer.new()
	_bgm_player.name = "BgmPlayer"
	_bgm_player.bus = String(BUS_BGM)
	_bgm_player.volume_db = SILENCE_DB
	_bgm_player.autoplay = false
	add_child(_bgm_player)

	_bgm_crossfade_player = AudioStreamPlayer.new()
	_bgm_crossfade_player.name = "BgmCrossfadePlayer"
	_bgm_crossfade_player.bus = String(BUS_BGM)
	_bgm_crossfade_player.volume_db = SILENCE_DB
	_bgm_crossfade_player.autoplay = false
	add_child(_bgm_crossfade_player)

	_ambient_player = AudioStreamPlayer.new()
	_ambient_player.name = "AmbientPlayer"
	_ambient_player.bus = String(BUS_AMBIENT)
	_ambient_player.volume_db = SILENCE_DB
	_ambient_player.autoplay = false
	add_child(_ambient_player)


func _build_sfx_pool() -> void:
	# M3W-7 — round-robin pool of AudioStreamPlayer nodes on the SFX bus.
	# Each entry is constructed once; play_sfx assigns the stream + calls
	# play() per call. AudioStreamPlayer reuses the underlying voice handle
	# so this is cheap.
	_sfx_pool.clear()
	for i in range(SFX_POOL_SIZE):
		var p: AudioStreamPlayer = AudioStreamPlayer.new()
		p.name = "SfxPool%d" % i
		p.bus = String(BUS_SFX)
		p.volume_db = FULL_DB
		p.autoplay = false
		add_child(p)
		_sfx_pool.append(p)


func _get_sfx_stream(cue_id: StringName) -> AudioStream:
	# Lazy-load the SFX stream on first request. Cache on the autoload so
	# subsequent plays don't re-decode.
	if _sfx_streams.has(cue_id):
		return _sfx_streams[cue_id]
	var path: String = SFX_PATHS[cue_id]
	var stream: AudioStream = load(path) as AudioStream
	if stream == null:
		# Use WarningBus so the universal-warning-gate test catches a missing
		# SFX asset at CI / soak time. Not push_warning directly — that bypasses
		# the gate.
		var wb: Node = get_tree().root.get_node_or_null("WarningBus") if is_inside_tree() else null
		if wb != null and wb.has_method("warn"):
			wb.warn("[AudioDirector] failed to load SFX %s" % path, &"audio")
		else:
			push_warning("[AudioDirector] failed to load SFX %s" % path)
		return null
	_sfx_streams[cue_id] = stream
	return stream


func _next_sfx_player() -> AudioStreamPlayer:
	# Round-robin advance. If the next slot is still mid-play, we still kick
	# it — that voice cuts off and the new cue takes over. With pool size 8
	# this is rarely audible (older cue is in its decay tail).
	if _sfx_pool.is_empty():
		return null
	var p: AudioStreamPlayer = _sfx_pool[_sfx_pool_index]
	_sfx_pool_index = (_sfx_pool_index + 1) % _sfx_pool.size()
	return p


func _get_stream_s2_bgm() -> AudioStream:
	if _stream_s2_bgm == null:
		_stream_s2_bgm = load(STREAM_PATH_S2_BGM) as AudioStream
		if _stream_s2_bgm == null:
			push_warning("[AudioDirector] failed to load %s" % STREAM_PATH_S2_BGM)
			return null
		_set_stream_loop(_stream_s2_bgm, true)
	return _stream_s2_bgm


func _get_stream_s2_boss() -> AudioStream:
	if _stream_s2_boss == null:
		_stream_s2_boss = load(STREAM_PATH_S2_BOSS) as AudioStream
		if _stream_s2_boss == null:
			push_warning("[AudioDirector] failed to load %s" % STREAM_PATH_S2_BOSS)
			return null
		_set_stream_loop(_stream_s2_boss, true)
	return _stream_s2_boss


func _get_stream_s2_ambient() -> AudioStream:
	if _stream_s2_ambient == null:
		_stream_s2_ambient = load(STREAM_PATH_S2_AMBIENT) as AudioStream
		if _stream_s2_ambient == null:
			push_warning("[AudioDirector] failed to load %s" % STREAM_PATH_S2_AMBIENT)
			return null
		_set_stream_loop(_stream_s2_ambient, true)
	return _stream_s2_ambient


## Mark an OGG / WAV stream as looped. Both `AudioStreamOggVorbis` and
## `AudioStreamWAV` expose `loop` (different sub-properties), so we set
## whichever one exists rather than hard-coding the class.
func _set_stream_loop(stream: AudioStream, value: bool) -> void:
	if stream == null:
		return
	# AudioStreamOggVorbis.loop is a bool property.
	if "loop" in stream:
		stream.set("loop", value)


## Fade out the BGM player, fade in the new stream on the crossfade player,
## then swap node roles so the crossfade player becomes the canonical BGM
## player. Net effect: future calls (e.g. another `crossfade_to_*` or
## `stop_all_music`) operate on the right player without ambiguity.
func _crossfade_bgm(new_stream: AudioStream, fade_ms: int) -> void:
	if _bgm_player == null or _bgm_crossfade_player == null:
		return
	# Kill any in-flight fades so we don't double-tween volume.
	if _bgm_fade_tween != null and _bgm_fade_tween.is_valid():
		_bgm_fade_tween.kill()
	if _bgm_crossfade_tween != null and _bgm_crossfade_tween.is_valid():
		_bgm_crossfade_tween.kill()
	# Start the new track silent on the crossfade player.
	_bgm_crossfade_player.stream = new_stream
	_bgm_crossfade_player.volume_db = SILENCE_DB
	_bgm_crossfade_player.play()
	# Tween both volumes in parallel.
	var duration_sec: float = max(fade_ms, 1) / 1000.0
	_bgm_crossfade_tween = create_tween()
	_bgm_crossfade_tween.set_parallel(true)
	_bgm_crossfade_tween.tween_property(_bgm_crossfade_player, "volume_db", FULL_DB, duration_sec)
	_bgm_crossfade_tween.tween_property(_bgm_player, "volume_db", SILENCE_DB, duration_sec)
	# After fade completes, swap so _bgm_player owns the new track. We bind
	# the swap as a deferred call so the tween's "finished" callback runs
	# off the property update path.
	_bgm_crossfade_tween.finished.connect(_finalize_crossfade)


func _finalize_crossfade() -> void:
	if _bgm_player == null or _bgm_crossfade_player == null:
		return
	# Stop the old (now-silent) BGM player.
	if _bgm_player.playing:
		_bgm_player.stop()
	# Swap roles by exchanging the variable references — both players sit on
	# the same bus and are functionally interchangeable, so a name/role swap
	# avoids re-instantiating the streams.
	var tmp: AudioStreamPlayer = _bgm_player
	_bgm_player = _bgm_crossfade_player
	_bgm_crossfade_player = tmp
	# Re-prep the (now idle) crossfade player.
	_bgm_crossfade_player.volume_db = SILENCE_DB


func _play_with_fade_in(player: AudioStreamPlayer, stream: AudioStream, fade_ms: int) -> void:
	if player == null or stream == null:
		return
	if _bgm_fade_tween != null and _bgm_fade_tween.is_valid():
		_bgm_fade_tween.kill()
	player.stream = stream
	player.volume_db = SILENCE_DB
	player.play()
	var duration_sec: float = max(fade_ms, 1) / 1000.0
	_bgm_fade_tween = create_tween()
	_bgm_fade_tween.tween_property(player, "volume_db", FULL_DB, duration_sec)


# Ambient has its own tween slot so a BGM transition doesn't kill an in-flight
# ambient fade.
func _play_with_fade_in_ambient(player: AudioStreamPlayer, stream: AudioStream, fade_ms: int) -> void:
	if player == null or stream == null:
		return
	if _ambient_fade_tween != null and _ambient_fade_tween.is_valid():
		_ambient_fade_tween.kill()
	player.stream = stream
	player.volume_db = SILENCE_DB
	player.play()
	var duration_sec: float = max(fade_ms, 1) / 1000.0
	_ambient_fade_tween = create_tween()
	_ambient_fade_tween.tween_property(player, "volume_db", FULL_DB, duration_sec)


func _fade_out_and_stop(player: AudioStreamPlayer, fade_ms: int) -> void:
	if player == null:
		return
	var duration_sec: float = max(fade_ms, 1) / 1000.0
	var tween: Tween = create_tween()
	tween.tween_property(player, "volume_db", SILENCE_DB, duration_sec)
	tween.finished.connect(func() -> void:
		if player != null and player.playing:
			player.stop()
	)


# ---- Diagnostics -----------------------------------------------------

## Routes through DebugFlags.combat_trace (HTML5-only) so Sponsor's DevTools
## console (and the Playwright harness) can confirm S2 audio triggers
## actually fired. Same pattern as `Stratum1BossRoom._combat_trace`.
func _combat_trace(tag: String, msg: String = "") -> void:
	if not is_inside_tree():
		return
	var df: Node = get_tree().root.get_node_or_null("DebugFlags")
	if df != null and df.has_method("combat_trace"):
		df.combat_trace(tag, msg)
