extends Node2D
class_name S1YardChunk
## Painter for the S1 open cloister-YARD chunk (ticket 86ca5erzk T4; v2 ground-
## composition RE-DO 86ca5hwmx; #426 FINER-CELL + SEAMLESS-BLEND soak-revision).
## Paints an OPEN, VARIED ground expanse — NOT the four-walls-boxing-the-screen room
## model — into the `FloorTiles` + `PathLane` TileMapLayers at `_ready`.
##
## SPATIAL MODEL (the pivot — s1-cloister-yard.md §2): the yard is ONE big open
## traversable expanse, WIDER + TALLER than the 480x270 viewport so the camera scrolls
## in BOTH axes. There is NO perimeter wall ring. Buildings are landmark STRUCTURES.
##
## #426 FINER-CELL REVISION (Sponsor 2026-06-08, soak of 23ca119): "the path corners/
## steps are too chunky because the ground/path is painted on a coarse cell grid — one
## big cell = one big step. Make the ground tilemap use a MUCH FINER cell grid so path
## edges/corners become small smooth steps. KEEP the camera zoom + char/mob scale + the
## loved cobble STONE size." Two ground-resolution concepts are now DECOUPLED:
##
##   1. LOGICAL tile (32px) — the WORLD/spawn/port/ChunkDef contract. `grid_w/grid_h`
##      (40x24) and ALL authored geometry (`grass_regions`, `building_footprints`,
##      `well_apron`, `well_footprint`, `garden_bed`, the lane spine) stay in LOGICAL
##      tiles, diff-readable, UNCHANGED from 23ca119. The assembler/camera-bounds/
##      char-scale/spawns all still see the same 1280x768 world.
##   2. FINE cell (16px) — the painter's RENDER + GEOMETRY-DECISION grid, `CELL_SUBDIV`x
##      finer (2x → an 80x48 fine grid). Path-edge/region-boundary/lane-dip decisions are
##      made at fine resolution → corners step in 16px increments = small smooth steps
##      (the Sponsor "chunky" fix). The TileSet cell is 16px (`s1_cloister_yard.tres`,
##      regenerated by `tools/build_yard_tileset_tres.py`).
##
##   The cobble STONE size is UNCHANGED across the finer grid: each 128px-per-variant
##   atlas tile is now sliced into an 8x8 grid of 16px cells (was 4x4 of 32px) and the
##   painter addresses it CONTINUOUSLY by world coord (`fx % ATLAS_FINE_PERIOD`) so the
##   full seamless 128px texture reconstructs across an 8x8 fine-cell span = STILL 128
##   world-px. Finer cells resolve GEOMETRY, they do NOT shrink the stones.
##
## #426 SEAMLESS-BLEND REVISION (same soak): "make the materials BLEND — no more sharp
## tile seams between dirt/grass/cobble; feather dirt into grass + soften the path edge
## into the dirt (Stardew/Graveyard-Keeper soft dirt↔grass transition)." With the 2x-finer
## grid a multi-fine-cell DITHER BAND at each material boundary reads as the soft stipple
## transition the references show (Stardew literally dithers dirt↔grass at the edge):
##   - GRASS↔DIRT: P(grass) ramps over a `BLEND_BAND_CELLS`-wide band (signed distance to
##     the region edge, in fine cells); a per-cell hash dithers grass-vs-dirt across the
##     band → a soft feathered border, NOT a hard rectangle (`_grass_blend_at`).
##   - LANE-edge↔DIRT: the outermost lane band probabilistically falls back to dirt on the
##     same dither (applied in `_compute_lane_cells`) → the path edge softens into the earth.
##   - WELL APRON↔DIRT: the apron's outer ring feathers into dirt on the dither too.
##   These are SPATIAL dithers between TWO full-bleed seamless fields — they need NO new
##   authored transition tiles + NO Uma transition-doctrine (both materials already tile
##   seamlessly; the blend is the interleave, exactly the reference look). If a future
##   surface needs Wang/edge transition TILES with shared edge pixels, THAT is Uma's lane.
##
## V3 STRUCTURE (carried from 23ca119, Sponsor "no structure ... just chaos"): smooth
## continuous DIRT base field, ONE deliberate fine-cobble LANE, GRASS only at the margins,
## COBBLE only as the well apron. The finer grid + blend REFINE this structure; they do
## not change the hand-placed layout.
##
## Why a script-painter: TileMapLayer serialises painted cells as a binary PackedByteArray
## that is impossible to diff-review. Painting via `set_cell` in `_ready` is deterministic,
## diff-readable, and GUT-testable.
##
## COLLISION IS DECOUPLED: building collision is the StaticBody2D nodes built here (in
## LOGICAL-tile world rects); this script paints only the *visual* ground. NO floor collision.
##
## NO BAKED VEGETATION (spec §5): every WALKING tile ships ZERO green pixels. Grass is a
## SEPARATE composed GROUND material (source 4), painted as feathered patches.

# Atlas-source ids inside s1_cloister_yard.tres.
const SOURCE_COBBLE: int = 0  # surviving-paving COBBLE patches (well apron only, v3)
const SOURCE_WALL_FINE: int = 1
const SOURCE_PATH: int = 2  # the fine-cobble LANE (floor_path.png)
const SOURCE_DIRT: int = 3  # worn-DIRT majority field (floor_dirt.png)
const SOURCE_GRASS: int = 4  # GRASS reclamation tile (floor_grass.png)

## LOGICAL tile size (px) — the world/spawn/port/ChunkDef contract. UNCHANGED at 32px.
const TILE_PX: float = 32.0

## FINER-CELL revision (#426): the painter renders at `CELL_SUBDIV`x-finer cells so the
## path/region GEOMETRY resolves in small steps (the Sponsor "chunky corners" fix). 2x →
## a 16px fine cell (TILE_PX / CELL_SUBDIV). The TileSet cell size matches (16px).
const CELL_SUBDIV: int = 2
const FINE_CELL_PX: float = TILE_PX / float(CELL_SUBDIV)  # 16.0

## Each ground atlas is 768x128 = 6 variant-blocks, each variant a 128px-square seamless
## toroidal tile. Sliced at the 16px fine cell, one variant spans 8x8 fine cells
## (128/16). Continuous world-coord addressing wraps onto this period so the seamless
## 128px texture reconstructs with ZERO block seam — and the STONE size stays 128 world-px
## (the finer cell does NOT shrink the stones; it only resolves geometry finer).
const ATLAS_FINE_PERIOD: int = 8  # 128px variant / 16px fine cell

## The path atlas is the same 6-variant 768x128 layout; the lane scatters variants per
## (now-finer) BLOCK so it never reads a repeating stamp (spec §2.4). A path block is one
## variant tile = ATLAS_FINE_PERIOD fine cells wide.
const PATH_VARIANTS: int = 6
const COBBLE_VARIANTS: int = 6

## Continuous DIRT + GRASS fields paint from ONE variant each (the v3 seam fix —
## addressing one seamless toroidal tile continuously, NOT swapping variants per block,
## which produced the visible block grid). Variant 0 chosen arbitrarily.
const DIRT_FIELD_VARIANT: int = 0
const GRASS_FIELD_VARIANT: int = 0

## The finer-brick wall is a 128px atlas (now 8x8 of 16px cells). Building bricks address
## it by the fine world coord wrapped into the 8-cell period so coursing flows continuously.
const WALL_FINE_PERIOD: int = 8  # 128px wall atlas / 16px fine cell

## #426 SEAMLESS-BLEND: width (in FINE cells) of the dither band that feathers each material
## boundary. ~3 fine cells = ~48 world-px = the soft transition band width in the Stardew/
## Graveyard-Keeper refs. Across the band, P(keep-material) ramps 1.0 (interior) → 0.0
## (outside), dithered per fine cell → a soft organic stipple border, never a hard edge.
const BLEND_BAND_CELLS: int = 3

## Yard grid in LOGICAL tiles (32px). 40x24 @ 32px = 1280x768 world — the size_tiles the
## ChunkDef + assembler + camera-bounds all assume (pinned by the GUT test). @export so a
## downstream T7 chunk-extension can author a different size without a code edit.
@export var grid_w: int = 40
@export var grid_h: int = 24

## Seed for the per-block lane/cobble variant scatter (the repeat-break hash). Fixed so
## the yard's variant layout is deterministic across boots. NOT the per-character seed.
@export var cobble_seed: int = 1763

## Seed for the material-boundary feathered DITHER (grass borders, lane edges, apron edge).
## Deterministic per boot. Drives the seamless-blend stipple (#426), not a mid-field scatter.
@export var grass_seed: int = 2207

## HAND-PLACED GRASS REGIONS (v3) in LOGICAL tiles (x,y,w,h). Grass reclaims ONLY the OUTER
## edges/corners/margins — a FEW deliberate regions, NOT scattered across the middle. The
## region INTERIOR is solid grass; its border FEATHERS back to dirt over a multi-fine-cell
## dither band (#426 seamless blend), never a hard rectangle. Diff-reviewable data.
@export var grass_regions: Array[Rect2i] = [
	Rect2i(0, 0, 7, 6),  # NW corner
	Rect2i(33, 0, 7, 5),  # NE corner
	Rect2i(0, 18, 9, 6),  # SW corner (wettest, grassiest)
	Rect2i(34, 19, 6, 5),  # SE corner
	Rect2i(20, 0, 10, 2),  # thin N-rim strip
	Rect2i(22, 22, 11, 2),  # thin S-rim strip
]

## Surviving-COBBLE apron region (v3) in LOGICAL tiles — a deliberate paved ring around the
## well (the most-walked-and-paved spot). NO mid-field cobble scatter. Its outer ring
## feathers into dirt on the same dither band so the apron edge is soft.
@export var well_apron: Rect2i = Rect2i(19, 15, 4, 4)

## Building footprints in LOGICAL tiles (x,y,w,h) — landmark STRUCTURES standing IN the
## open expanse. The painter paints finer-brick over each AND builds a matching StaticBody2D.
@export var building_footprints: Array[Rect2i] = [
	Rect2i(8, 0, 12, 3),  # North range (chapel face / bell-tower)
	Rect2i(6, 21, 14, 3),  # South range (dormitory ruin)
	Rect2i(18, 9, 6, 5),  # Central cloister building
	Rect2i(33, 6, 3, 3),  # Far, small east outbuilding (depth)
]

## WELL-HEAD landmark in LOGICAL tiles (x,y,w,h) — solid base under the .tscn well sprite.
## SOAK-REVISION (#426 prior): 2x2 to match the well scale drop (a real well ~1.5x player).
@export var well_footprint: Rect2i = Rect2i(20, 16, 2, 2)

## SPRING pools (T8) — damp low/shadow corners (still dark warm-neutral ColorRect pools).
@export var spring_tiles: Array[Vector2i] = [
	Vector2i(28, 2),  # north — damp shadow under the chapel range east section
	Vector2i(9, 18),  # SW dip near the dormitory ruin
]

## GARDEN BED gone wild (T8) — ONE hero bed of tilled-soil-gone-to-weeds (south).
@export var garden_bed: Rect2i = Rect2i(12, 17, 4, 3)

## S1_YARD_WATER_DOCTRINE (Uma §3.3) — still, dark, warm-neutral, sub-1.0, NEVER pure-black.
const WATER_BASE := Color(0.180, 0.165, 0.149, 1.0)  # #2E2A26 dark warm-neutral still surface
const WATER_HIGHLIGHT := Color(0.522, 0.486, 0.424, 1.0)  # #857C6C sparse still catch
const GARDEN_SOIL := Color(0.329, 0.271, 0.184, 0.78)  # #54452F soil, semi-transparent

## Fine-grid dimensions (derived). The painter iterates these; geometry decisions map a
## fine cell back to its fractional LOGICAL tile.
var _fw: int = 0
var _fh: int = 0

@onready var _floor_tiles: TileMapLayer = $FloorTiles
@onready var _path_lane: TileMapLayer = $PathLane
@onready var _springs: Node2D = $Springs
@onready var _buildings: TileMapLayer = $Buildings
@onready var _building_bodies: Node2D = $BuildingBodies
@onready var _well_body: Node2D = $WellBody
@onready var _decoration: Node2D = $Decoration


func _ready() -> void:
	_fw = grid_w * CELL_SUBDIV
	_fh = grid_h * CELL_SUBDIV
	# Layer order (deliberate, hand-placed, finer grid + feathered blends):
	#   1. DIRT  — smooth continuous base across the WHOLE fine grid (seamless).
	#   2. GRASS — overwrite dirt in the authored edge/corner regions, FEATHERED.
	#   3. WELL APRON — surviving-cobble paved ring around the well, feathered edge.
	#   4. LANE  — the one clear fine-cobble PATH ribbon (finer-resolved dip), soft edges.
	# Later: building bricks, well/spring/garden/apron decoration.
	_paint_dirt_field()
	_paint_grass_regions()
	_paint_well_apron()
	_paint_path_lane()
	_build_structures()
	_build_well_collision()
	_paint_springs()
	_paint_garden_bed()
	_paint_building_aprons()
	_scatter_decoration()


# ---- PASS 1: continuous DIRT base field over the whole FINE grid --------------


## Paint the smooth continuous DIRT base field across the WHOLE fine grid. Each fine cell
## addresses the single dirt variant CONTINUOUSLY by its world coord wrapped into the
## variant's 8x8 fine cells → the seamless 128px tile wraps onto itself with NO block seam,
## and the STONE size stays 128 world-px (the finer cell does not shrink it). Pure-ish.
func _paint_dirt_field() -> void:
	if _floor_tiles == null:
		push_warning("S1YardChunk: FloorTiles TileMapLayer missing — cannot paint")
		return
	for fy in range(_fh):
		for fx in range(_fw):
			_floor_tiles.set_cell(
				Vector2i(fx, fy), SOURCE_DIRT, _field_atlas_coords(DIRT_FIELD_VARIANT, fx, fy)
			)


## Continuous atlas coords for a field (dirt/grass) variant, addressed by the FINE world
## cell wrapped into the variant's 8x8-fine-cell (128px) period → seamless self-tiling,
## constant stone size. Pure function (GUT-pinnable).
func _field_atlas_coords(variant: int, fx: int, fy: int) -> Vector2i:
	var local_x: int = ((fx % ATLAS_FINE_PERIOD) + ATLAS_FINE_PERIOD) % ATLAS_FINE_PERIOD
	var local_y: int = ((fy % ATLAS_FINE_PERIOD) + ATLAS_FINE_PERIOD) % ATLAS_FINE_PERIOD
	return Vector2i(variant * ATLAS_FINE_PERIOD + local_x, local_y)


# ---- PASS 2: GRASS regions with a feathered (seamless-blend) border -----------


## Overwrite dirt with GRASS in the authored edge/corner regions ONLY. Grass uses the SAME
## continuous addressing as dirt (variant 0) so a multi-cell grass region reads as one
## continuous patch. #426: the region border FEATHERS into the dirt over a multi-fine-cell
## dither band (`_grass_blend_at`) so the dirt↔grass edge is a soft stipple, NOT a hard rect.
func _paint_grass_regions() -> void:
	if _floor_tiles == null:
		return
	for fy in range(_fh):
		for fx in range(_fw):
			if _grass_blend_at(fx, fy):
				_floor_tiles.set_cell(
					Vector2i(fx, fy), SOURCE_GRASS, _field_atlas_coords(GRASS_FIELD_VARIANT, fx, fy)
				)


## True if a FINE cell renders GRASS, with a SEAMLESS feathered border (#426). A cell is
## grass if it is inside a grass region's INTERIOR (solid), OR within the region's outer
## blend band where a per-cell dither passes against a probability that RAMPS from ~1.0
## just inside the edge to ~0.0 at the band's outer reach → a soft organic dirt↔grass
## stipple, never a hard rectangle. Operates on fine cells (so the feather is 16px-fine).
## Deterministic (grass_seed drives only the dither). Pure function (GUT-pinnable).
func _grass_blend_at(fx: int, fy: int) -> bool:
	# Inward distance (in FINE cells) from the NEAREST grass-region edge: >0 inside, the
	# larger the deeper into the region. Cells outside every region report a sentinel < 0.
	var depth: int = _grass_edge_depth(fx, fy)
	if depth == -2147483648:
		return false  # outside every region
	# Deep interior (beyond the blend band) = solid grass.
	if depth >= BLEND_BAND_CELLS:
		return true
	# Within the blend band (depth 0..BLEND_BAND_CELLS-1): ramp P(grass) from high (deep)
	# to low (edge) and dither. depth 0 = the very edge cell. Map depth → keep-probability.
	var p_keep: float = float(depth + 1) / float(BLEND_BAND_CELLS + 1)  # 0..1, rises inward
	return _fine_dither(Vector2i(fx, fy)) < p_keep


## Inward depth (in FINE cells) of fine cell (fx,fy) relative to the grass regions: the
## min over all containing regions of the cell's distance to that region's nearest edge
## (0 = on the edge, larger = deeper inside). Returns INT_MIN if the cell is in NO region.
## Regions are authored in LOGICAL tiles; convert the fine cell to its logical tile to test
## containment, and measure edge distance in FINE cells (logical edge distance * CELL_SUBDIV
## plus the sub-tile offset) so the feather resolves at the finer grid.
func _grass_edge_depth(fx: int, fy: int) -> int:
	var best: int = -2147483648
	for region: Rect2i in grass_regions:
		# Fine-cell bounds of this logical region.
		var rx0: int = region.position.x * CELL_SUBDIV
		var ry0: int = region.position.y * CELL_SUBDIV
		var rx1: int = (region.position.x + region.size.x) * CELL_SUBDIV - 1
		var ry1: int = (region.position.y + region.size.y) * CELL_SUBDIV - 1
		if fx < rx0 or fx > rx1 or fy < ry0 or fy > ry1:
			continue
		# Distance (fine cells) to the nearest of the four edges.
		var d: int = min(min(fx - rx0, rx1 - fx), min(fy - ry0, ry1 - fy))
		best = max(best, d)
	return best


# ---- PASS 3: surviving-COBBLE well apron (feathered edge) ---------------------


## The surviving-COBBLE well APRON. Cobble appears in FloorTiles ONLY here — a deliberate
## paved ring around the well. Overwrites dirt/grass within `well_apron`; the well_footprint
## interior is left (the well prop occupies it) and the lane pass still wins. #426: the
## apron's OUTER ring feathers into dirt on the dither band so the apron edge is soft, not a
## hard rect. Uses the cobble atlas with per-block variant scatter (high-freq stones mask
## any variant edge across this small region). Fine-grid.
func _paint_well_apron() -> void:
	if _floor_tiles == null:
		return
	var ax0: int = well_apron.position.x * CELL_SUBDIV
	var ay0: int = well_apron.position.y * CELL_SUBDIV
	var ax1: int = (well_apron.position.x + well_apron.size.x) * CELL_SUBDIV - 1
	var ay1: int = (well_apron.position.y + well_apron.size.y) * CELL_SUBDIV - 1
	for fy in range(ay0, ay1 + 1):
		for fx in range(ax0, ax1 + 1):
			if fx < 0 or fx >= _fw or fy < 0 or fy >= _fh:
				continue
			# Leave the well's own footprint interior unpaved (the well prop sits there).
			if _logical_rect_has_fine(well_footprint, fx, fy):
				continue
			# Feather the apron's outer ring into dirt: depth from the apron edge, dither.
			var d: int = min(min(fx - ax0, ax1 - fx), min(fy - ay0, ay1 - fy))
			if d < BLEND_BAND_CELLS:
				var p_keep: float = float(d + 1) / float(BLEND_BAND_CELLS + 1)
				if _fine_dither(Vector2i(fx, fy)) >= p_keep:
					continue  # feathered back to dirt (already painted) — soft apron edge
			var block_x: int = fx / ATLAS_FINE_PERIOD
			var block_y: int = fy / ATLAS_FINE_PERIOD
			var variant: int = _block_variant(block_x, block_y)
			var atlas := _scatter_atlas_coords(variant, fx, fy)
			_floor_tiles.set_cell(Vector2i(fx, fy), SOURCE_COBBLE, atlas)


## Continuous atlas coords for a SCATTERED-variant surface (cobble apron / path lane): the
## chosen `variant` block, addressed by the FINE world cell wrapped into the 8-fine-cell
## period → constant stone size, seamless within the block. Pure.
func _scatter_atlas_coords(variant: int, fx: int, fy: int) -> Vector2i:
	var local_x: int = ((fx % ATLAS_FINE_PERIOD) + ATLAS_FINE_PERIOD) % ATLAS_FINE_PERIOD
	var local_y: int = ((fy % ATLAS_FINE_PERIOD) + ATLAS_FINE_PERIOD) % ATLAS_FINE_PERIOD
	return Vector2i(variant * ATLAS_FINE_PERIOD + local_x, local_y)


## True if FINE cell (fx,fy) falls inside a LOGICAL-tile rect. Pure helper.
func _logical_rect_has_fine(rect: Rect2i, fx: int, fy: int) -> bool:
	var lx0: int = rect.position.x * CELL_SUBDIV
	var ly0: int = rect.position.y * CELL_SUBDIV
	var lx1: int = (rect.position.x + rect.size.x) * CELL_SUBDIV - 1
	var ly1: int = (rect.position.y + rect.size.y) * CELL_SUBDIV - 1
	return fx >= lx0 and fx <= lx1 and fy >= ly0 and fy <= ly1


## Fine high-frequency dither in [0,1] for the seamless-blend feather. Deterministic
## (grass_seed). Pure function.
func _fine_dither(cell: Vector2i) -> float:
	var h: int = ((cell.x * 2654435761) ^ (cell.y * 40503) ^ (grass_seed * 2246822519)) & 0x7fffffff
	return float(h % 1000) / 1000.0


# ---- PASS 4: the fine-cobble LANE (finer-resolved dip + soft edges) -----------


## Compute the set of FINE cells the LANE occupies (v2 §2 desire-line map), resolved at the
## FINE grid so the dip curve steps in small 16px increments (the #426 "chunky corners" fix).
## The lane is a HUMBLE worn footpath threading the ground:
##   - SPINE: west gate (player spawn, logical row 12) → gentle south dip → east descent.
##     3 LOGICAL tiles wide (= 6 fine cells), centred on `_spine_center_fine_row`.
##   - WELL SPUR: a short narrow spur from the spine S to the well apron.
## Cells inside a building/well footprint are EXCLUDED (a path never crosses a solid wall).
## Returns Dictionary{Vector2i(fine): true}.
func _compute_lane_cells() -> Dictionary:
	var cells: Dictionary = {}
	# Lane half-width in FINE cells: a 3-logical-tile-wide lane = 6 fine cells → ±3.
	var half_w: int = (3 * CELL_SUBDIV) / 2  # 3
	for fx in range(0, _fw):
		var center_fy: int = _spine_center_fine_row(fx)
		for dy in range(-half_w, half_w + 1):
			# #426 SOFT PATH EDGE: the OUTERMOST band (|dy| == half_w) feathers into dirt on
			# the dither (keep ~65%, drop ~35%) so the path edge softens into the surrounding
			# earth (Stardew/Graveyard-Keeper) WITHOUT reading ragged. The interior band
			# (|dy| < half_w) always keeps (the solid walkable core).
			if absi(dy) == half_w and _fine_dither(Vector2i(fx, center_fy + dy)) >= 0.65:
				continue
			_add_lane_cell(cells, fx, center_fy + dy)
	# WELL SPUR: a short narrow (2-fine-cell-wide) spur from the spine S to the apron top.
	# Start it INSIDE the always-kept lane core (center + half_w - 1) so the spur is
	# guaranteed 4-connected to the spine (the soft-edge feather only drops the outermost
	# band, so starting one cell inside the rim keeps the spur attached).
	var spur_fx: int = (well_footprint.position.x) * CELL_SUBDIV + CELL_SUBDIV  # ~1 logical tile in
	var spur_top: int = _spine_center_fine_row(spur_fx) + half_w - 1
	var apron_top_fine: int = well_apron.position.y * CELL_SUBDIV
	for fy in range(spur_top, apron_top_fine):
		_add_lane_cell(cells, spur_fx, fy)
		_add_lane_cell(cells, spur_fx + 1, fy)  # 2-fine-cell-wide spur (still narrow)
	return cells


## Spine centre-row at FINE column fx — a gentle south dip, now resolved at the fine grid so
## the curve steps in 16px increments (smooth) instead of the prior 32px stairs. Anchored at
## logical row 12 (= fine row 24), dipping ~2 LOGICAL tiles (= 4 fine cells) south across the
## mid-yard. Pure (GUT-pinnable, deterministic).
func _spine_center_fine_row(fx: int) -> int:
	var t: float = float(fx) / float(maxi(_fw - 1, 1))  # 0..1 across the yard
	var dip_fine: float = sin(t * PI) * 2.0 * float(CELL_SUBDIV)  # 0 at ends, ~4 fine cells at centre
	return 12 * CELL_SUBDIV + int(round(dip_fine))


## Add a lane FINE cell at (fx,fy) IF in-bounds and NOT inside a building/well footprint.
## #426 SOFT EDGE: the OUTERMOST lane band (the top/bottom fine row of the 6-wide band)
## probabilistically falls back to dirt on the dither so the path edge feathers into the
## surrounding earth (Stardew/Graveyard-Keeper soft path edge), instead of a hard cobble cut.
func _add_lane_cell(cells: Dictionary, fx: int, fy: int) -> void:
	if fx < 0 or fx >= _fw or fy < 0 or fy >= _fh:
		return
	for foot: Rect2i in building_footprints:
		if _logical_rect_has_fine(foot, fx, fy):
			return
	if _logical_rect_has_fine(well_footprint, fx, fy):
		return
	cells[Vector2i(fx, fy)] = true


## Paint the fine-cobble LANE into PathLane AND erase the ground beneath in FloorTiles (AC9:
## exactly ONE tile-class per cell, no z-fight). The soft path edge is already applied in
## `_compute_lane_cells` (the outermost spine band feathers into dirt), so every cell in the
## returned set is painted. Variant scatter (per FINE block) keeps the lane from reading a
## repeating stamp (§2.4).
func _paint_path_lane() -> void:
	if _path_lane == null or _floor_tiles == null:
		push_warning("S1YardChunk: PathLane/FloorTiles missing — cannot paint the lane")
		return
	var cells: Dictionary = _compute_lane_cells()
	for cell: Vector2i in cells:
		var block_x: int = cell.x / ATLAS_FINE_PERIOD
		var block_y: int = cell.y / ATLAS_FINE_PERIOD
		var variant: int = _path_block_variant(block_x, block_y)
		var atlas := _scatter_atlas_coords(variant, cell.x, cell.y)
		_path_lane.set_cell(cell, SOURCE_PATH, atlas)
		# Erase ground beneath → one tile-class per cell (the AC9 anti-z-fight rule).
		_floor_tiles.set_cell(cell, -1)


## Pick a path variant [0, PATH_VARIANTS) for a fine BLOCK via a non-tiling hash. Distinct
## prime mix from _block_variant so the lane + ground variant fields don't realign. Pure.
func _path_block_variant(block_x: int, block_y: int) -> int:
	var h: int = (block_x * 49979693) ^ (block_y * 86028157) ^ (cobble_seed * 6151)
	return absi(h) % PATH_VARIANTS


## Pick a cobble variant [0, COBBLE_VARIANTS) for a fine BLOCK via a non-tiling hash. Pure.
func _block_variant(block_x: int, block_y: int) -> int:
	var h: int = (block_x * 73856093) ^ (block_y * 19349663) ^ (cobble_seed * 83492791)
	return absi(h) % COBBLE_VARIANTS


# ---- Structures, collision, decoration (LOGICAL-tile world rects) -------------


## Build the cloister BUILDINGS as solid landmark structures: paint finer-brick into the
## `Buildings` TileMapLayer (fine cells over each LOGICAL footprint) AND add a StaticBody2D.
func _build_structures() -> void:
	for foot: Rect2i in building_footprints:
		_paint_building_bricks(foot)
		_add_building_collision(foot)


## Paint finer-brick over a building footprint into the `Buildings` TileMapLayer at the FINE
## grid. The brick atlas window is phase-locked to the FINE world cell (wrapped into the
## 8-cell wall period) so coursing flows continuously across a multi-tile building face.
func _paint_building_bricks(foot: Rect2i) -> void:
	if _buildings == null:
		return
	var fx0: int = foot.position.x * CELL_SUBDIV
	var fy0: int = foot.position.y * CELL_SUBDIV
	var fx1: int = (foot.position.x + foot.size.x) * CELL_SUBDIV - 1
	var fy1: int = (foot.position.y + foot.size.y) * CELL_SUBDIV - 1
	for fy in range(fy0, fy1 + 1):
		for fx in range(fx0, fx1 + 1):
			if fx < 0 or fx >= _fw or fy < 0 or fy >= _fh:
				continue
			var atlas := Vector2i(fx % WALL_FINE_PERIOD, fy % WALL_FINE_PERIOD)
			_buildings.set_cell(Vector2i(fx, fy), SOURCE_WALL_FINE, atlas)


## Add a StaticBody2D + RectangleShape2D over a building footprint (LOGICAL-tile world rect)
## so the building is solid (walk-around). World position is UNCHANGED from 23ca119 (the
## finer cell does not move buildings — collision is in world px from the logical footprint).
func _add_building_collision(foot: Rect2i) -> void:
	if _building_bodies == null:
		return
	var body := StaticBody2D.new()
	body.name = "Building_%d_%d" % [foot.position.x, foot.position.y]
	var shape := CollisionShape2D.new()
	var rect := RectangleShape2D.new()
	rect.size = Vector2(foot.size.x * TILE_PX, foot.size.y * TILE_PX)
	shape.shape = rect
	body.position = Vector2(
		(foot.position.x + foot.size.x * 0.5) * TILE_PX,
		(foot.position.y + foot.size.y * 0.5) * TILE_PX
	)
	body.add_child(shape)
	_building_bodies.add_child(body)


## Build the well-head collision — a StaticBody2D over `well_footprint` (LOGICAL-tile world
## rect, position UNCHANGED). Walk-AROUND solid like the buildings.
func _build_well_collision() -> void:
	if _well_body == null:
		return
	var foot := well_footprint
	var body := StaticBody2D.new()
	body.name = "WellHeadBody"
	var shape := CollisionShape2D.new()
	var rect := RectangleShape2D.new()
	rect.size = Vector2(foot.size.x * TILE_PX, foot.size.y * TILE_PX)
	shape.shape = rect
	body.position = Vector2(
		(foot.position.x + foot.size.x * 0.5) * TILE_PX,
		(foot.position.y + foot.size.y * 0.5) * TILE_PX
	)
	body.add_child(shape)
	_well_body.add_child(body)


## Paint the SPRING pools (T8) — still dark warm-neutral ColorRect pools (sub-1.0, NEVER
## pure-black). Positions in LOGICAL-tile world px (UNCHANGED). NO Polygon2D, NO tween, NO
## moss_patch sprites (the #426 spiky-prop "trash" class was removed — water is the feature).
func _paint_springs() -> void:
	if _springs == null:
		return
	for center: Vector2i in spring_tiles:
		var cx: float = (float(center.x) + 0.5) * TILE_PX
		var cy: float = (float(center.y) + 0.5) * TILE_PX
		var pool := ColorRect.new()
		pool.color = WATER_BASE
		pool.size = Vector2(TILE_PX * 1.6, TILE_PX * 1.4)
		pool.position = Vector2(cx - pool.size.x * 0.5, cy - pool.size.y * 0.5)
		_springs.add_child(pool)
		var glint := ColorRect.new()
		glint.color = WATER_HIGHLIGHT
		glint.size = Vector2(TILE_PX * 0.5, TILE_PX * 0.28)
		glint.position = Vector2(cx - glint.size.x * 0.5, cy - TILE_PX * 0.35)
		_springs.add_child(glint)


## Paint the GARDEN BED gone wild (T8) — ONE hero damp-soil ColorRect bed (LOGICAL-tile world
## px, UNCHANGED). The moss_patch overgrowth was removed (#426 spiky-prop "trash" class).
func _paint_garden_bed() -> void:
	if _springs == null:
		return
	var bed := garden_bed
	var soil := ColorRect.new()
	soil.color = GARDEN_SOIL
	soil.size = Vector2(bed.size.x * TILE_PX, bed.size.y * TILE_PX)
	soil.position = Vector2(bed.position.x * TILE_PX, bed.position.y * TILE_PX)
	_springs.add_child(soil)


## Damp shadow aprons at building south bases (T8) — a subtle dark ColorRect strip grounding
## each building into the yard (LOGICAL-tile world px, UNCHANGED). NO moss_patch tufts (#426).
func _paint_building_aprons() -> void:
	if _springs == null:
		return
	for foot: Rect2i in building_footprints:
		var apron_y: int = foot.position.y + foot.size.y
		if apron_y >= grid_h:
			continue  # building runs to the grid edge (off-frame) — no visible south base
		var apron := ColorRect.new()
		apron.color = Color(0.16, 0.15, 0.13, 0.32)  # damp-shadow darken, sub-1.0, low alpha
		apron.size = Vector2(foot.size.x * TILE_PX, TILE_PX * 0.6)
		apron.position = Vector2(foot.position.x * TILE_PX, apron_y * TILE_PX)
		_springs.add_child(apron)


## Yard decoration. INTENTIONALLY a NO-OP (Sponsor scale soak, PR #424): the prior moss_patch
## tuft scatter read as oversized ugly spiky blobs. The vegetation story is carried by the
## grass GROUND material; T3 owns proper proportional ground-vegetation props.
func _scatter_decoration() -> void:
	pass
