#!/usr/bin/env python3
"""
Rebuild resources/tilesets/s1_cloister_yard.tres at a FINER cell size (#426 soak-rev,
Sponsor 2026-06-08 "path corners/steps too chunky — make the cell grid much finer").

WHY A FINER CELL: the path dip + material boundaries stepped in whole 32px increments
-> chunky stair-step corners. Halving the TileSet cell to 16px (a 2x-finer grid) lets the
painter resolve path edges/corners in 16px steps = small smooth steps. The WORLD pixel
size is UNCHANGED (the painter grid doubles 40x24 -> 80x48 so 80*16=1280, 48*16=768 ==
the 40*24*32 world the assembler/camera/char-scale all assume). The cobble STONE size is
ALSO unchanged: each 128px-per-variant atlas tile is now sliced into an 8x8 grid of 16px
cells (was 4x4 of 32px), and the painter addresses the atlas CONTINUOUSLY by world coord
(`tx % 8, ty % 8`) so the full seamless 128px texture is reconstructed across an 8x8 cell
span = still 128 world-px. Stones do NOT shrink — only the GEOMETRY grid gets finer.

Exact-division note (the constraint that fixed the cell size at 16px, not the Sponsor's
loose "~20 of a tile"): the world (1280x768) AND the 128px atlas period must BOTH divide
the cell evenly. 16px -> grid 80x48 (int) + atlas period 8 (int): clean. 12px (2.67x) and
10px (3.2x) break both. 8px (4x) divides but exceeds the brief's "2-3x" + quadruples cell
count. 16px (2.0x) is the only clean-division choice inside the 2-3x band — chosen.

Atlas textures are UNCHANGED (same floor_*.png bytes, same stones). Only the .tres cell
geometry (32->16) + the cell-declaration grid (4x4 -> 8x8 per variant) change. This script
regenerates the whole .tres deterministically so the 768x128 atlases re-slice exactly.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))
OUT = os.path.join(ROOT, "resources/tilesets/s1_cloister_yard.tres")

CELL = 16            # finer cell (was 32) — 2x-finer geometry grid, stones unchanged
ATLAS_W, ATLAS_H = 768, 128     # all four ground atlases (6 variants x 4x4 of 32px)
WALL_W, WALL_H = 128, 128       # finer-brick wall atlas (4x4 of 32px)

# Cell columns/rows when each atlas is sliced at CELL px.
GROUND_COLS, GROUND_ROWS = ATLAS_W // CELL, ATLAS_H // CELL   # 48 x 8 at CELL=16
WALL_COLS, WALL_ROWS = WALL_W // CELL, WALL_H // CELL          # 8 x 8 at CELL=16


def atlas_cells(cols, rows):
    """Emit the `c:r/0 = 0` cell-declaration lines for a cols x rows atlas grid."""
    lines = []
    for r in range(rows):
        for c in range(cols):
            lines.append(f"{c}:{r}/0 = 0")
    return "\n".join(lines)


HEADER = """[gd_resource type="TileSet" load_steps=7 format=3 uid="uid://b0embergrave_s1yard_tileset"]

; S1 cloister-YARD TileSet — ticket 86ca5erzk (T4) + the v2 GROUND-COMPOSITION RE-DO
; (86ca5hwmx) + the #426 FINER-CELL soak-revision (Sponsor 2026-06-08: "path corners/
; steps too chunky — make the cell grid much finer").
;
; CELL SIZE = 16px (was 32px). HALVING the cell to a 2x-finer geometry grid lets the
; painter resolve the path lane's dip + every material boundary in 16px steps instead of
; chunky 32px stairs (the Sponsor "chunky corners" flag). The WORLD size is UNCHANGED:
; the painter grid doubles to 80x48 so 80*16 == 40*32 == 1280 (and 48*16 == 24*32 == 768)
; — the assembler/camera-bounds/char-scale all still see the same 1280x768 world. The
; cobble STONE size is ALSO unchanged: each 128px-per-variant atlas tile is now an 8x8
; grid of 16px cells (was 4x4 of 32px), addressed CONTINUOUSLY by world coord so the full
; seamless 128px texture reconstructs across an 8x8 cell span = still 128 world-px. The
; finer cell is for path/region GEOMETRY resolution ONLY — it does NOT shrink the stones.
;
; The atlas PNGs are byte-identical to the v2 RE-DO (same floor_*.png stones). Only the
; .tres cell geometry (texture_region_size 32->16 + the cell-declaration grid 4x4->8x8 per
; variant + tile_size 32->16) changed. Five atlas sources (geometry only; palette is in
; the PNGs):
;
;   Source 0 = floor_cobble.png  -> LOVED ground cobble (well apron). 768x128.
;   Source 1 = wall_cloister_fine.png -> finer-brick building face. 128x128.
;   Source 2 = floor_path.png    -> fine-cobble LANE (warmer+lighter, finer stones). 768x128.
;   Source 3 = floor_dirt.png    -> worn-DIRT majority field (stone-free noise). 768x128.
;   Source 4 = floor_grass.png   -> GRASS reclamation tile (edges/corners). 768x128.
;
; DEAD: floor_slab.png (ashlar, third rejection) + floor_sandstone.png (rejected twice).
;
; AC9 paint-not-stack: each tile-class is painted into its OWN TileMapLayer with exactly
; ONE class rendering per cell (the cell is erased in the other layers), z=0, no z-fight
; (html5-export.md §Z-index). This .tres is REGENERATED by tools/build_yard_tileset_tres.py
; — edit that script (CELL constant) to re-slice, do NOT hand-edit the cell declarations.

[ext_resource type="Texture2D" path="res://assets/tilesets/s1_cloister/floor_cobble.png" id="1_cobble"]
[ext_resource type="Texture2D" path="res://assets/tilesets/s1_cloister/wall_cloister_fine.png" id="2_wall_fine"]
[ext_resource type="Texture2D" path="res://assets/tilesets/s1_cloister/floor_path.png" id="3_path"]
[ext_resource type="Texture2D" path="res://assets/tilesets/s1_cloister/floor_dirt.png" id="4_dirt"]
[ext_resource type="Texture2D" path="res://assets/tilesets/s1_cloister/floor_grass.png" id="5_grass"]
"""


def atlas_source(sub_id, ext_id, cols, rows):
    return (
        f'[sub_resource type="TileSetAtlasSource" id="{sub_id}"]\n'
        f'texture = ExtResource("{ext_id}")\n'
        f"texture_region_size = Vector2i({CELL}, {CELL})\n"
        f"{atlas_cells(cols, rows)}\n"
    )


def main():
    parts = [HEADER, ""]
    parts.append(atlas_source("TileSetAtlasSource_cobble", "1_cobble", GROUND_COLS, GROUND_ROWS))
    parts.append(atlas_source("TileSetAtlasSource_wall_fine", "2_wall_fine", WALL_COLS, WALL_ROWS))
    parts.append(atlas_source("TileSetAtlasSource_path", "3_path", GROUND_COLS, GROUND_ROWS))
    parts.append(atlas_source("TileSetAtlasSource_dirt", "4_dirt", GROUND_COLS, GROUND_ROWS))
    parts.append(atlas_source("TileSetAtlasSource_grass", "5_grass", GROUND_COLS, GROUND_ROWS))
    parts.append(
        "[resource]\n"
        f"tile_size = Vector2i({CELL}, {CELL})\n"
        'sources/0 = SubResource("TileSetAtlasSource_cobble")\n'
        'sources/1 = SubResource("TileSetAtlasSource_wall_fine")\n'
        'sources/2 = SubResource("TileSetAtlasSource_path")\n'
        'sources/3 = SubResource("TileSetAtlasSource_dirt")\n'
        'sources/4 = SubResource("TileSetAtlasSource_grass")\n'
    )
    with open(OUT, "w", newline="\n", encoding="utf-8") as f:
        f.write("\n".join(parts))
    print(f"[tileset] wrote {OUT}")
    print(f"[tileset] CELL={CELL}px  ground={GROUND_COLS}x{GROUND_ROWS} cells  "
          f"wall={WALL_COLS}x{WALL_ROWS} cells  (atlas period {128 // CELL} cells/variant)")


if __name__ == "__main__":
    main()
